version: "2"
services:
    web:
        build: .
        environment:
            - NODE_ENV=production
            - PORT=80
            - DB_HOST=mysql
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - DB_DATABASE=onehour
            - DEBUG=app:*
        volumes:
            - ./:/usr/src/app
        links:
            - mysql
        ports:
            - '80:80'
    mysql:
        image: mysql:5.7
        volumes:
            - './.data/mysql:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=onehour

